### ISSUE TITLE
unable to deploy on heroku

### ISSUE THREAD

**Issue by Dare-Devill** [gsoosk/TelegramSpotifyDownloader#1]
heroku says python error plz solve

**Comment by ghost** [comment]
I deployed bot on Heroku Today ; it's Working ...
btw
If You facing Error like :- this python version isn't Supported on Heroku-20 , Try Changing Python version .

**Comment by Dare-Devill** [comment]
From where...?

**Comment by ghost** [comment]
try Adding app.json,Procfile and heroku button Maybe it will work for you too . Or Copy those stuffs from my fork ..

**Comment by chsaiujwal** [comment]
> try Adding app.json,Procfile and heroku button Maybe it will work for you too . Or Copy those stuffs from my fork ..

Hey, I tried to fork yours abs deploy but I got a error... 


`2021-02-07T02:33:42.049247+00:00 app[worker.1]: 2021-02-07 02:33:42,047 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
2021-02-07T02:33:42.049283+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-07T02:33:42.049284+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
2021-02-07T02:33:42.049284+00:00 app[worker.1]:     handler.handle_update(update, self, check, context)
2021-02-07T02:33:42.049290+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telegram/ext/handler.py", line 117, in handle_update
2021-02-07T02:33:42.049291+00:00 app[worker.1]:     return self.callback(update, context)
2021-02-07T02:33:42.049291+00:00 app[worker.1]:   File "main.py", line 25, in get_single_song_handler
2021-02-07T02:33:42.049292+00:00 app[worker.1]:     authenticate(bot, update)
2021-02-07T02:33:42.049293+00:00 app[worker.1]:   File "main.py", line 73, in authenticate
2021-02-07T02:33:42.049293+00:00 app[worker.1]:     username = update.message.chat.username
2021-02-07T02:33:42.049305+00:00 app[worker.1]: AttributeError: 'CallbackContext' object has no attribute 'message'`

**Comment by Dare-Devill** [comment]
Not found in your profile...

**Comment by ghost** [comment]
> Not found in your profile...

deleted ..

**Comment by ghost** [comment]
> > Not found in your profile...
> 
> deleted ..

Bro there is no deploy button then how can we deploy, please explain the steps to deploy on heroku

**Comment by ghost** [comment]
> > > Not found in your profile...
> > 
> > 
> > deleted ..

I deleted my fork , but irizona's fork of mine still there .
https://github.com/irizuna/TGspotifyDL
> 
> Bro there is no deploy button then how can we deploy, please explain the steps to deploy on heroku

**Comment by gsoosk** [comment]
This has been fixed in the latest commit. 
https://github.com/gsoosk/TelegramSpotifyDownloader/issues/4
